### PR TITLE
feature/new-editing-flow

### PR DESCRIPTION
**Pull request by mmahdigh**

### CODE REVIEW

**Comment by mmahdigh** [comment]
Fixes #152 #151 #153 #176

**Comment by mmahdigh** [comment]
image

Exact error messages for invalid values are still not implemented. The above design is for the time we were editing percentages, but now that we are editing OP amounts, there's no room for the ! sign.

This is what it looks like right now:

image

**Review by kristoferlund — CHANGES_REQUESTED** [review]
image

- Create list is available even though ranking treshold is not met yet
- Create list menu option have different font size than above item

image

- Ranking screen button still says `Finish`. It should be `Continue`.

image

- Popovers not implemented?

image
- For category where ranking treshold is met, there should be the menu item `Edit manually` which marks category as `Finished` and allows me to edit manually.

image

- Successfully creating a list does not open the confirmation dialog with links to Agora etc.

image

- Status is still listed as `In progress` after list has been created. 

Or.. it does not seem like backend have registered that list has been created. I am getting a 403:

image

... I'll stop here :) Have a look at the referenced issues and make sure you cover all cases we have discussed. And if anything is unclear, just ping me. ✨

**Comment by mmahdigh** [comment]
@kristoferlund The issues you raised are all fixed (except for the popovers and editing errors, which I'll implement together later).

Please review it again.

**Comment by mmahdigh** [comment]
Also, let's keep an eye on this error that sometimes happens:

image

I'm not sure if this PR is causing it or it's something internal broken in Metamask.  @kristoferlund

**Review by kristoferlund — CHANGES_REQUESTED** [review]
image

- Clicking on `Edit manually` on ranking screen calls `/flow/finish` with 403 as response. Server and frontend seem to have different opinions on when the ranking threshold is met. I did 18 rankings in category "Community Building". UI said threshold was 17. 
- Oh.. continued ranking. At 29% ranked, still same error.

### Create list from pairwise screen
- pinJSONToIPFS takes 90 seconds to complete and then returns a 524 (timeout) error.
- List creation proceeds even though there was an error with pinJSONToIPFS
- After attestation is created, `/flow/finish` is called with 403 as response. "You need to vote for the minimum threshold times"

**Comment by kristoferlund** [comment]
@mmahdigh I merging this to be able to fix some small UI issues.

**Pull request merged**
